# Generated by Django 4.2.5 on 2023-09-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urinestrip_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urinestrip',
            name='colors_json',
        ),
    ]
