# Generated by Django 4.2.5 on 2023-09-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urinestrip_app', '0002_remove_urinestrip_colors_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urinestrip',
            name='image',
            field=models.ImageField(upload_to='urinestrip_app/urinestrips/'),
        ),
    ]
